### ISSUE TITLE
I m bad @ js

### ISSUE THREAD

**Issue by mrmrs** [mrmrs/viminfo#1]
Ran npm install and node index.js and got this error. I couldn't figure out how to fix it. Is something wrong with my setup? Help me @jongold you are my only hope.

```
~/p/vinfo (master)$ node index.js
/Users/mrmrs/p/vinfo/src/commands.js:1
(function (exports, require, module, __filename, __dirname) { const { append, compose, countBy, filter, head, identity, map, match, prop,
                                                                    ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)


    at Object.<anonymous> (/Users/mrmrs/p/vinfo/index.js:3:18)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
```

**Comment by howardroark** [comment]
Maybe just use old fashioned JS?  It's not so bad! ;)

**Comment by jem-computer** [comment]
Sorry, forgot to say that this requires `node@>=6.0` for now until I bother doing some kind of transpilation.
